spring:
  application:
    name: elk

  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

#for logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  logstash:
    enabled: true
    host: localhost
    port: 5000
  pattern:
    level: '%5p'
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'